export const Path = {
  landing: '/',
  register: '/register',
  login: '/login',
  home: '/dashboard/home',
  tasks: '/dashboard/tasks',
  course: '/dashboard/course',
  subjects: '/dashboard/subjects/',
  subject: '/dashboard/subjects/:idSubject',
  calendar: '/dashboard/calendar',
  notes: '/dashboard/notes',
  exams: '/dashboard/exams',
  createSubject: '/dashboard/subjects/createSubject',
  createCourse: '/dashboard/courses/createCourse',
}