export const Path = {
  landing: '/',
  register: '/register',
  login: '/login',
  home: '/dashboard/home',
  tasks: '/dashboard/tasks',
  course: '/dashboard/course',
  subjects: '/dashboard/subjects/',
  subject: '/dashboard/subjects/:idSubject',
  calendar: '/dashboard/calendar',
  createSubject: '/dashboard/subjects/createSubject',
  editSubject: '/dashboard/subjects/editSubject',
  createCourse: '/dashboard/course/createCourse',
  createTask: '/dashboard/tasks/createTask',
  editCourse: '/dashboard/course/editCourse',
  editTask: '/dashboard/tasks/editTask/:idTask',
}
